name: main

on:
  push:
    branches:
    - main
  schedule:
  - cron: '15 8 * * *'
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - run: pip install pre-commit-mirror-maker

    - run: |
        git config --global user.name "Adam's Bot"
        git config --global user.email 'bot@adamj.eu'

    - run: pre-commit-mirror . --language node --package-name dprint --types text --entry 'dprint fmt --allow-no-files' --id dprint --description 'A pluggable and configurable code formatting platform written in Rust.'

    - run: git push origin HEAD:refs/heads/main --tags
